"""followers

Revision ID: 15785ce51ba9
Revises: df4103bf4915
Create Date: 2023-02-24 08:34:16.850315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15785ce51ba9'
down_revision = 'df4103bf4915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
